### ISSUE TITLE
Investigate conditional search spaces

### ISSUE THREAD

**Issue by cooperlab** [PathologyDataScience/glimr#22]
See if conditional search spaces are compatible with PBT and ASHA schedulers. 

They are not compatible with most search algorithms, but search algorithms are not currently working anyway.

**Comment by lawrence-chillrud** [comment]
A [Ray Tune docs page](https://docs.ray.io/en/releases-2.0.1/tune/tutorials/tune-search-spaces.html#how-to-use-custom-and-conditional-search-spaces) that may prove helpful with this.

**Comment by cooperlab** [comment]
This is addressed by @RaminNateghi in the new MIL model wrappers.

We found that conditional spaces have pretty broad support. The tricky part is when using PBT, you have to exclude conditional variables from your mutation list. The new glimr.util functions handle this exclusion.
