### ISSUE TITLE
Allow for custom stopper object

### ISSUE THREAD

**Issue by lawrence-chillrud** [PathologyDataScience/glimr#47]
Update Search class to include method to set custom trial or experiment stopper. Should probably include some error handling as well, check that the stopper passed is of a certain allowable type.

**Comment by cooperlab** [comment]
I think this is important enough for the user that it should be exposed in the class interface.

**Comment by cooperlab** [comment]
My suggestion `TrialPlateauStopper` with sensible parameters as the default option if `None` is passed. Support {`TrialPlateauStopper`, `MaximumIterationStopper`, `ExperimentPlateauStopper`, `TimeOutStopper`}.
