### ISSUE TITLE
Integrate K-fold cross-validation into glimr tuning

### ISSUE THREAD

**Issue by RaminNateghi** [PathologyDataScience/glimr#59]
@cooperlab , currently for tuning we are using a config dictionary that enables us to search through different configurations and select the best model. However, the data pipeline is still fixed for all the trials, which means all the trials use the same train/validation sets [Fig.1]. 
It would be interesting to resample data automatically during tuning, i.e. generate train/validation subsets during tuning [Fig. 2]. 
This would allow us to train various models independently through distinct training/validation sets, which enable us to do ensemble tuning, a valuable approach to deal with overfitting issue, particularly in situations with limited data.

**[Fig. 1]**
<img width="500" alt="Screenshot 2023-11-29 at 13 04 28" src="https://github.com/PathologyDataScience/glimr/assets/65801650/306af88e-4d51-4843-8bc7-afc1b5c4f361">

**[Fig. 2]**
<img width="1089" alt="Screenshot 2023-11-29 at 13 54 49" src="https://github.com/PathologyDataScience/glimr/assets/65801650/04dc1847-a39f-4969-a0d9-6492f80d9425">

The common resampling technique is k-fold cross validation (cv), but we can use other resampling methods.  
I think we need to consider the following items if we want to implement that:

1. Update search space so we can resample data during tuning using k-fold cv. This can be done by passing an index into the data loader.
2. Write a wrapper to analyse the logs generated by trials to extract fold-specific information, models, etc.
3. Each trial should be run on a specific resampled data

**Comment by cooperlab** [comment]
I like how you abstracted this beyond just supporting k-fold cross validation.

I think the "data" portion of the config are just kwargs for the data loader. That is very flexible, and so the user can put anything they want in there. Maybe the tricky part for the user is how to generate the trials they want - i.e. repeats of the same config with different data parameters. This could be assisted with a function, or just demonstrated via example and documented.

I agree with the steps above. Let's focus concretely on k-fold cross validation for now, keeping ensembling in mind as a next step.

**Comment by RaminNateghi** [comment]
OK, thank you for the comments. One question is do we need to repeat the same model's config for different data parameters? For example, is it necessary for the configurations of both `model i` and `model i+1` in Fig.2 to be same?

**Comment by cooperlab** [comment]
> OK, thank you for the comments. One question is do we need to repeat the same model's config for different data parameters? For example, is it necessary for the configurations of both `model i` and `model i+1` in Fig.2 to be same?

I'm not sure if I'm understanding correctly. For a k-fold cross validation you would need K trials with identical configurations.

**Comment by RaminNateghi** [comment]
OK, yes, the configurations should be the same in CV.  In fact, in K-fold CV we train the same model _k_ times on different data (but in ensemble learning we tend to train _k_ different models on the same data).

**Comment by cooperlab** [comment]
> OK, yes, the configurations should be the same in CV. In fact, in K-fold CV we train the same model _k_ times on different data (but in ensemble learning we tend to train _k_ different models on the same data).

I think the relationship between k-fold CV and ensembling is that we will have post-processing functions that parse and analyze trial results. Beyond that, I don't think that ensembling needs to modify the data that are processed in each trial. Unless you are trying to do the bootstrap sampling as is done in Random Forests.

**Comment by RaminNateghi** [comment]
done in https://github.com/PathologyDataScience/glimr/pull/60!
