### ISSUE TITLE
Fix trial numbering mismatch in the experiment_table function

### ISSUE THREAD

**Issue by Tilly-S** [PathologyDataScience/glimr#62]
Here is the suggested code fix:

import re
trials = []
subdirs = os.listdir(exp_dir)
for i, subdir in enumerate(subdirs):
    if subdir.startswith(“trainable”) and os.path.isdir(
        os.path.join(exp_dir, subdir)
    ):
        trial_num = re.search(r’(?:[^_]*_){3}(\d+)’, subdir).group(1)
        result_path = os.path.join(exp_dir, subdir, “result.json”)
        if os.path.exists(result_path):
            trial = pd.read_json(result_path, lines=True)
            trial.insert(0, “trial_#“, trial_num)
            trial.insert(1, “subdir”, subdir)
            trial.insert(2, “exp_dir”, exp_dir)
            trials.append(trial)
df = pd.concat(trials, ignore_index=True)

**Comment by cooperlab** [comment]
Check this regex to make sure it's not project specific.

**Comment by RaminNateghi** [comment]
fixed in https://github.com/PathologyDataScience/glimr/pull/63.
